import java.util.*
Public class Sum of PosandNeg
   {
     int a[]={1,2,3,-4,-5,6,7,8,-9,10}
          int psum o=n sum=0
            for (i=o;i<a.length;i++)
                 if(a[i]>0)
                 pSum=nsum +a[i];
               else
                 nsum = n sum +a[i];
                }
      system.out.Println("Sum of Positive number="+Psum)
      system.out.Println("Sum of nagative number="+n sum)
